### PR TITLE
Add glossary feature

### PR DESCRIPTION
**Pull request by zubairnahmed**
Made request for changes PR 335.
https://github.com/LearnersGuild/curriculum/pull/335

### CODE REVIEW

**Comment by deadlyicon** [comment]
the tests fail!

**Comment by deadlyicon** [comment]
please write tests for `digest/glossary.js` in `digest/glossary.test.js`

**Comment by zubairnahmed** [comment]
The tests for all the digests live in index.test.js --- should we just add our glossary tests there? Currently your instructions tell us to create another file for the glossary test - this would break the file organization pattern. Thoughts?

**Comment by zubairnahmed** [comment]
We'll follow the existing pattern unless you say otherwise!

**Comment by zubairnahmed** [comment]
This is the only test we can muster. Is it good for you?

```js
describe('.glossary', function(){
      it('should be an object with correct keys', function(){
        const glossaryIds = this.digest.glossary
        expect(glossaryIds.Function).to.exist;
        expect(glossaryIds.HTTP).to.exist;
      })
    })
```

**Comment by deadlyicon** [comment]
```js
describe('digest', function(){
  describe('.glossary', function(){
    it('should be an object', function() {
      expect(digest.glossary).to.be.a('object')
      expect(digest.glossary).to.not.be.an('array')
    })
    it('should contain terms', function(){
      expect(Object.keys(digest.glossary).length).to.be.gt(0)
    })
    describe('[term]', function(){
      
      let term
      beforeEach(function(){
        const termId = Object.keys(digest.glossary)[0]
        term = digest.glossary[termId]
      })

      it('should be an object', function(){
        expect(term).to.be.a('object')
      })

      it('should have an id', function(){
        expect(term.id).to.be.a('string')
      })

      it('should have a value', function(){
        expect(term.value).to.be.a('string')
      })

      it('should have a path', function(){
        expect(term.path).to.be.a('string')
      })
    })
  })
})
```

**Comment by hhhhhaaaa** [comment]
Thank you!

**Pull request closed without merging**
